build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armv6: "ghcr.io/home-assistant/armv6-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
  i386: "hcr.io/home-assistant/i386-base-debian:bookworm"

labels:
  org.opencontainers.image.title: "Arqut Tunnel CE"
  org.opencontainers.image.description: "Arqut Tunnel CE Service"
  org.opencontainers.image.source: "https://github.com/arqut/arqut-ha-addon-ce"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
